title: easySensors blog
tagline: showing our products here
email: easy.sensors@gmail.com
description: >-
  This website will display our products valuable tips and the code 
url: "https://easysensors.github.io" # the base hostname & protocol for   site
author: easySensors team
#twitter:
#  username: itspatrq
#  card: summary
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
# Build settings
markdown: kramdown
remote_theme: ItsPatrq/minimal-music-project
permalink: /:title.html
pagination:
  enabled: true
  per_page: 20
  limit: 0
  sort_field: 'date'
  sort_reverse: true

  exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
#  - docs/
  - node_modules
